"""update course and level models

Revision ID: 029f6d6a7207
Revises: 364ec3509867
Create Date: 2026-07-30 20:07:23.111059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029f6d6a7207'
down_revision: Union[str, Sequence[str], None] = '364ec3509867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.sql import func

def upgrade() -> None:
    # Courses
    op.add_column(
        "courses",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=func.now(),
            nullable=False,
        ),
    )

    op.alter_column(
        "courses",
        "created_at",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="created_at::timestamp",
    )

    # Enrollments
    op.add_column(
        "enrollments",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=func.now(),
            nullable=False,
        ),
    )

    # Levels
    op.add_column(
        "levels",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=func.now(),
            nullable=False,
        ),
    )

    op.alter_column(
        "levels",
        "created_at",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="created_at::timestamp",
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('levels', 'updated_at')
    op.drop_column('enrollments', 'created_at')
    op.alter_column('courses', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('courses', 'updated_at')
    # ### end Alembic commands ###
