"""update progress and submission models

Revision ID: 19ca757d5cae
Revises: 029f6d6a7207
Create Date: 2026-07-30 20:33:05.480940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '19ca757d5cae'
down_revision: Union[str, Sequence[str], None] = '029f6d6a7207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.alter_column(
        "level_progress",
        "updated_at",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="updated_at::timestamp",
    )

    op.add_column(
        "submissions",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=func.now(),
            nullable=False,
        ),
    )

    op.alter_column(
        "submissions",
        "stdout",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )

    op.alter_column(
        "submissions",
        "stderr",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'stderr',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('submissions', 'stdout',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('submissions', 'created_at')
    op.alter_column('level_progress', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
