"""update challenge models

Revision ID: 52139533380f
Revises: 19ca757d5cae
Create Date: 2026-07-30 21:01:08.554677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '52139533380f'
down_revision: Union[str, Sequence[str], None] = '19ca757d5cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
 



op.alter_column('challenges', 'business_scenario',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
op.alter_column('challenges', 'starter_code',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
op.alter_column('challenges', 'solution',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
op.alter_column('challenges', 'explanation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('challenges', 'solution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('challenges', 'starter_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('challenges', 'business_scenario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
