"""update career path models

Revision ID: 811130d5a9c1
Revises: cd9bc6edd6ae
Create Date: 2026-08-06 18:16:06.331303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811130d5a9c1'
down_revision: Union[str, Sequence[str], None] = 'cd9bc6edd6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_reports', sa.Column('generated_by', sa.String(length=50), nullable=False))
    op.alter_column('career_reports', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('career_roadmaps', 'report_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('career_roadmaps', 'report_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('career_reports', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('career_reports', 'generated_by')
    # ### end Alembic commands ###
