"""add progress checkpoints

Revision ID: 95a68472ef26
Revises: d45d76ec9ebc
Create Date: 2026-08-03 12:55:35.297192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95a68472ef26'
down_revision: Union[str, Sequence[str], None] = 'd45d76ec9ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level_progress', sa.Column('checkpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('level_progress', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level_progress', 'completed_at')
    op.drop_column('level_progress', 'checkpoints')
    # ### end Alembic commands ###
