"""update submission table

Revision ID: d45d76ec9ebc
Revises: 8c7ff2bfebef
Create Date: 2026-08-02 23:55:39.501210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd45d76ec9ebc'
down_revision: Union[str, Sequence[str], None] = '8c7ff2bfebef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('challenges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('submissions', sa.Column('passed', sa.Boolean(), nullable=False))
    op.add_column('submissions', sa.Column('passed_count', sa.Integer(), nullable=False))
    op.add_column('submissions', sa.Column('total_count', sa.Integer(), nullable=False))
    op.add_column('submissions', sa.Column('xp_earned', sa.Integer(), nullable=False))
    op.add_column('submissions', sa.Column('time_ms', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'time_ms')
    op.drop_column('submissions', 'xp_earned')
    op.drop_column('submissions', 'total_count')
    op.drop_column('submissions', 'passed_count')
    op.drop_column('submissions', 'passed')
    op.alter_column('challenges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('challenges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
